push:
  name: Push
  fields:
    content:
      name: Content
      description: "The content you want displayed on the Tidbyt."
      required: false
      selector:
        select:
          options:
            - label: Washer
              value: washer
            - label: Dryer
              value: dryer
            - label: Dishwasher
              value: dishwasher
            - label: Coffee Maker
              value: coffee
            - label: Doorbell
              value: doorbell
            - label: HVAC Filters
              value: filters
            - label: Close Fridge
              value: fridge
            - label: Trash Day
              value: trash
            - label: Trash & Recycling Day
              value: TrashRecycle
    customcontent:
      name: Custom Content
      description: "Type the name of the custom content you want to display. Example: For custom you added 'example.star' to /config/tidbyt then you would type 'example' here. For text content, type in the text you want displayed."
      required: false
      selector:
        text:
    contenttype:
      name: Content Type
      description: "Select between the built-in content or custom content. Custom content should be a .star file placed inside /config/tidbyt."
      required: true
      default: "builtin"
      selector:
        select:
          options:
            - label: Built-In
              value: builtin
            - label: Custom
              value: custom
            - label: Text
              value: text
    devicename:
      name: Device Name
      description: "The Tidbyt device you want content to be displayed to. Make sure this matches the name you set in the configuration. Example: if you set the name to 'mytidbyt' then enter 'mytidbyt' here."
      required: true
      selector:
        text:
publish:
  name: Publish
  fields:
    content:
      name: Content
      description: "Type the name of the custom content you want to add to your regular app rotation. Example: For custom you added 'example.star' to /config/tidbyt then you would type 'example' here."
      required: true
      selector:
        text:
    contentid:
      name: Content ID
      description: "A unique name for your app."
      required: true
      selector:
        text:
    devicename:
      name: Device Name
      description: "The Tidbyt device you want content to be displayed to. Make sure this matches the name you set in the configuration. Example: if you set the name to 'mytidbyt' then enter 'mytidbyt' here."
      required: true
      selector:
        text: